config/routes.rb
EUProVeterinaria::Application.routes.draw do
 

root 'welcome#index'
resources :pets do
    resources :appointments, except: [:index,:delete]
end

resources :owners do
  get :pets, on: :member
end

resources :animals
resources :doctors

get "/login" => "sessions#new"
post "/login" => "sessions#create"
delete "/logout" => "sessions#destroy"

get "/profile" => "doctors#show"
get "/edit_profile" => "doctors#edit"

end

app/models/animal.rb
class Animal < ActiveRecord::Base
	has_many :pets
	validates_presence_of :name

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
	belongs_to :pet
	belongs_to :doctor
	validates_presence_of :description, :amount, :pet_id
	validates_numericality_of :amount, greater_than: 0
	
end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
has_secure_password validations: false
has_many :appointments

validates_presence_of :name, :email
validates :email, uniqueness: true

	def sum_of_appointments
		self.appointments.sum(:amount)
	end
end

app/models/owner.rb
class Owner < ActiveRecord::Base
	has_many :pets

	validates_presence_of :name, :last_name, :phone

end

app/models/pet.rb
class Pet < ActiveRecord::Base
	belongs_to :owner
	belongs_to :animal
	has_many :appointments
	
	validates_presence_of :name
	validates :observations, length: {maximum: 200}

	before_create :check_photo
	before_update :check_photo

	def sum_of_appointments
		self.appointments.sum(:amount)
	end

	protected

	def check_photo
		if pet_url.blank?
			self.pet_url = "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Pou.png/220px-Pou.png"
		end
	end

end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  def index
  	@animals = Animal.order(:name)
  end

  def new
  	@animal = Animal.new
  end

  def create
  	@animal = Animal.new(animal_params)
  	if @animal.save
  		redirect_to animals_path, notice: "El nuevo tipo de Animal ha sido exitosamente agregada."
  	else
  		flash[:error] = "Error al ingresar el tipo de Animal, Favor corregir los errores."
  		render :new
  	end
  end

  def edit
  	@animal = Animal.find(params[:id])
  end

  def update
  	@animal = Animal.find(params[:id])
  	if @animal.update_attributes(animal_params)
  		redirect_to animals_path, notice: "El tipo de animal se actualizo correctamente."
    else
      render :edit
    end
  end

  def destroy
  	@animal = Animal.find(params[:id])
  	@animal.destroy
  	redirect_to animals_path	
  end

   protected
  def animal_params
  	params.require(:animal).permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user
  before_action :authenticate

  def login(doctor)
    session[:doctor_id] = doctor.id
    redirect_to profile_path
  end

  def logout
    reset_session
    redirect_to root_path
  end

  def current_user
    if session[:doctor_id]
      @current_user = Doctor.find(session[:doctor_id])
    end
  end

  def authenticate
    unless current_user
        redirect_to login_path
    end
  end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  def new
  	@pet = Pet.find(params[:pet_id])
  	@appointment = @pet.appointments.build
  end

  def create
  	@pet = Pet.find(params[:pet_id])
  	@appointment = @pet.appointments.build(appointment_params)
  	@appointment.doctor = @current_user
    @doctor = @current_user
    if @appointment.save
      Usermailer.create_appointment(@doctor, @appointment, @pet).deliver
  		redirect_to @pet
  	else
  		render :new
  	end
  end

  def show
    @pet = Pet.find(params[:pet_id])
    @appointment = Appointment.find(params[:id])
    @doctor = Doctor.find(@current_user.id)
  end

  def edit
    @pet = Pet.find(params[:pet_id])
    @appointment = Appointment.find(params[:id])
    @doctor = Doctor.find(@current_user.id)
  end

  def update
    @pet = Pet.find(params[:pet_id])
    @appointment = Appointment.find(params[:id])
    @doctor = Doctor.find(@current_user.id)
    if @appointment.update_attributes(appointment_params)
      redirect_to @pet
    else
      render :edit
    end
  end

  protected

  def appointment_params
  	params.require(:appointment).permit(:description, :amount)
  end

end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
	  skip_before_action :authenticate, only: [:new, :create]
  def new
		 @doctor = Doctor.new	
	end

  def show
    @doctor = Doctor.find(@current_user.id)
  end

	def create
	@doctor = Doctor.new(doctor_params)
  	if @doctor.save 
      Usermailer.welcome_email(@doctor).deliver
  		redirect_to profile_path, notice: "El Doctor se agrego exitosamente" 
  	else
  		flash[:error] = "No se pudo registrar el doctor, Favor corregir los siguientes errores: "
  		render :new
  	end
	end

  def edit
    @doctor = Doctor.find(@current_user.id)
  end

  def update
    @doctor = Doctor.find(@current_user.id)

    if @doctor.update_attributes(doctor_params)
      Usermailer.notificate_user_update(@doctor).deliver
      redirect_to profile_path
    else
       render :edit
    end
  end


	protected
  def doctor_params
  	params.require(:doctor).permit(:name, :email, :password)
  end
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  def index
  	@owners = Owner.order(:id)
  end

  def pets
    @owner = Owner.find(params[:id])
    @pet = @owner.pets
  end

  def show
  	@owner = Owner.find(params[:id])
  end
  
  def new
  	@owner = Owner.new	
  end

  def create
  	@owner = Owner.new(owner_params)
  	if @owner.save 
  		redirect_to owners_path, notice: "El Propietario se agrego exitosamente" 
  	else
  		flash[:error] = "No se pudo registrar el propietario, Favor corregir los siguientes errores: "
  		render :new
  	end
  end

  def edit
  	@owner = Owner.find(params[:id])
  end

  def update
  	@owner = Owner.find(params[:id])

  	if @owner.update_attributes(owner_params)
  		redirect_to @owner, notice: "El Propietario se actualizo exitosamente"
  	else
  	   render :edit
  	end
  end

  def destroy
  	@owner = Owner.find(params[:id])
  	@owner.destroy
  	redirect_to owners_path  	
  end

  protected
  def owner_params
  	params.require(:owner).permit(:name, :last_name, :address, :phone, :email)
  end

end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  def index
  	@pets = Pet.order(:name)
  end

  def show
  	@pet = Pet.find(params[:id])
  end

  def new  
    @pet = Pet.new
  end

  def create
  	@pet = Pet.new(pet_params)
  	if @pet.save
  		redirect_to pets_path, notice: "La mascota ha sido exitosamente agregada."
  	else
  		flash[:error] = "Error al ingresar la mascota, Favor corregir los errores."
  		render :new
  	end
  end

  def edit
  	@pet = Pet.find(params[:id])
  end

  def update
  	@pet = Pet.find(params[:id])
  	if @pet.update_attributes(pet_params)
  		redirect_to pets_path, notice: "La mascota se actualizo correctamente."
    else
      render :edit
    end

  end

  def destroy
  	@pet = Pet.find(params[:id])
  	@pet.destroy
  	redirect_to pets_path
  end

  protected
  def pet_params
  	params.require(:pet).permit(:name, :born_at, :observations, :animal_id, :pet_url)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate, only: [:new, :create]

  def new
  	if current_user
  		redirect_to profile_path
  	end
  end

  def create
  	email = params[:session][:email]
  	password = params[:session][:password]

  	@doctor = Doctor.find_by_email(email)

  	if @doctor && @doctor.authenticate(password)
  		login(@doctor)
  	else
  		redirect_to login_path, flash: { error: "Email o Password incorrecto"}
  	end
  end

  def destroy
  	logout
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authenticate
  def index
  end
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def nice_date(fecha)
		return nil unless fecha
		fecha.strftime("%A, %d de %B de %Y")
	end

end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
	def owner_index_title
		content_tag(:h1, "Propietarios registrados en el sistema")
	end

	def owner_index_description
		content_tag(:p1, "Informacion General de los propietarios: ")
	end

end

app/helpers/pet_helper.rb
module PetHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/animals/_animal.html.erb
<tr>
	<td><%= animal.id %></td>
	<td><%= animal.name %></td>
	<td><%= link_to edit_animal_path(animal) do %>
		<span class="fa fa-edit"></span>
		Editar Animal
	<% end %>
	</td>
	<td><%= link_to "Eliminar", animal, method: :delete, data: {confirm: "Estas Seguro?"}  %> </td>
</tr>

app/views/animals/_form.html.erb
	<div class="form-group">
		<%=	f.label :name, "Nombre: " %>
		<%=	f.text_field :name, class: "form-control" %>
	</div>

app/views/animals/edit.html.erb
<h1>Editar Mascotas</h1>
<p><em>Verificar los siguientes datos: </em></p>

<%= render partial: "shared/errors", locals: { obj: @animal } %>

<%= form_for @animal do |f| %>
	<%= render partial: "form", locals: {f: f} %>

	<div class="btn-group" role="group" aria-label="Acciones">
		<%= button_tag(type: 'submit', class: "btn btn-default") do %>
			<i class="icon-ok icon-white"></i> Actualizar
		<% end %>
		
		<%= link_to "Cancelar", animals_path, class: "btn btn-default" %>
	</div>

<%- end %>

app/views/animals/index.html.erb
<h1>Veterinaria Chansey</h1>
<p>Atendido por las mas entrenadas enfermeras Joy</p>

	<% if flash[:notice] %>
	<div style="background: yellow">
		<%= flash[:notice] %>
	</div>
<% end %>

<table border="2" class="table table-hover table-bordered">
	<thead>
	<tr>
		<th>ID</th>
		<th>Nombre</th>
		<th colspan="2">
			Acciones
		</th>
	</tr>
	</thead>
	<tbody>
			<%= render @animals %>
	</tbody>
</table>

<div class="btn-group" role="group">
	<%= link_to "Agregar Animal", new_animal_path, class: "btn btn-default" %>
</body>

app/views/animals/new.html.erb
<h1>Crear un nuevo Tipo de Animal</h1>
<p><em>Ingrese los siguientes datos: </em></p>

<%= render partial: "shared/errors", locals: { obj: @animal } %>

<%= form_for @animal do |f| %>
<%= render partial: "form", locals: {f: f} %>
	
<div class="btn-group" role="group" aria-label="Acciones">
	<%= button_tag(type: 'submit', class: "btn btn-default") do %>
			<i class="icon-ok icon-white"></i> Crear Animal
<% end %>

<%= link_to "Cancelar", animals_path, class: "btn btn-default" %>

<%- end %>

app/views/appointments/_appointment.html.erb
<tr>
	<td><%= link_to appointment.id, [appointment.pet, appointment] %></td>
	<td><%= nice_date(appointment.created_at) %></td>
	<td><%= appointment.doctor_id %></td>
	<td><%= appointment.amount %></td>
</tr>

app/views/appointments/_form.html.erb
<div class="form-group">
	<%= f.label :description, "Descripcion: " %>
	<%= f.text_area :description, class: "form-control", placeholder: "Ingrese el dictamen..." %>
</div>
<div class="form-group">
	<%= f.label :amount, "Monto a Pagar: " %> 
	<%= f.number_field :amount, class: "form-control" %> 
</div>

app/views/appointments/edit.html.erb
<h1>Editar Cita</h1>

<%= render partial: "shared/errors", locals: { obj: @appointment } %>

<%= form_for [@pet, @appointment] do |f| %>
	<%= render partial: "form", locals: {f: f} %>
	
	<div class="btn-group" role="group" aria-label="Acciones">
		<%= button_tag(type: 'submit', class: "btn btn-default") do %>
			<i class="icon-ok icon-white"></i> Actualizar
	<% end %>

	<%= link_to "Cancelar", @pet, class: "btn btn-default" %>
<%- end %>

app/views/appointments/new.html.erb
<h1>Crear nueva Cita</h1>
<p><em>Ingrese los siguientes datos: </em></p>

<%= render partial: "shared/errors", locals: { obj: @appointment } %>

<%= form_for [@pet, @appointment] do |f| %>
	<%= render partial: "form", locals: {f: f} %>
	
	<div class="btn-group" role="group" aria-label="Acciones">
		<%= button_tag(type: 'submit', class: "btn btn-default") do %>
			<i class="icon-ok icon-white"></i> Actualizar
	<% end %>

	<%= link_to "Cancelar", @pet, class: "btn btn-default" %>
<%- end %>

app/views/appointments/show.html.erb
<h1><b> <%= @pet.name + " Cita Numero: " + @appointment.id.to_s %> </b></h1>

<p> <i> <%= @appointment.description %> <i></p>
<hr> </hr>
<ul>
	<li>
		<strong>ID: </strong>
		<%= @appointment.id %>
	</li>
	<li>
		<strong>Fecha: </strong>
		<%= nice_date(@appointment.created_at) %>
	</li>

	<hr>
	<%= link_to "Cancelar", @pet, class: "btn btn-default" %>
	<%= link_to "Editar Cita", edit_pet_appointment_path, class: "btn btn-default" %>

app/views/doctors/_doctor_appointments.html.erb
<% if appointments.any? %>
	<div>
		<h2>Citas hechas: </h2>
<table border="2" class="table table-hover table-bordered">
			<thead>
				<th>ID</th>
				<th>Fecha</th>
				<th>Doctor</th>
				<th>Monto Pagado</th>
			</thead>
			<tbody>
			<%= render appointments %>
			</tbody>
		</table>
	</div>
<% else %>
	<p><em>No tiene citas registradas aun.</em></p>
<% end %>

app/views/doctors/_form.html.erb
<div class="form-group">
	<%= f.label :name, "Nombre: " %>
	<%= f.text_field :name, class: "form-control"%>
</div>
<div class="form-group">
	<%= f.label :email, "Correo Electronico: " %>
	<%= f.email_field :email , class: "form-control"%>
</div>
<div class="form-group">
	<%= f.label :password, "Contrasena" %>
	<%= f.password_field :password, class: "form-control" %>
</div>

app/views/doctors/edit.html.erb
<h1>Editar Usuario</h1>

<%= render partial: "shared/errors", locals: { obj: @doctor } %>

<%= form_for @doctor do |f| %>
	<%= render partial: "form", locals: {f: f} %>
	<div class="btn-group" role="group" aria-label="Acciones">
		<%= button_tag(type: 'submit', class: "btn btn-default") do %>
			<i class="icon-ok icon-white"></i> Actualizar
		<% end %>
		<%= link_to "Cancelar", @doctor, class: "btn btn-default"%>
<%- end %>

app/views/doctors/index.html.erb
<h1>Doctors#index</h1>
<p>Find me in app/views/doctors/index.html.erb</p>

app/views/doctors/new.html.erb
<h1>Crear nuevo Doctor</h1>
<p><em>Ingrese los siguientes datos: </em></p>

<%= render partial: "shared/errors", locals: { obj: @doctor } %>

<%= form_for @doctor do |f| %>
	<%= render partial: "form", locals: {f: f} %>

<div class="btn-group" role="group" aria-label="Acciones">
	<%= button_tag(type: 'submit', class: "btn btn-default") do %>
			<i class="icon-ok icon-white"></i> Crear Doctor
<% end %>
		<%= link_to "Cancelar", login_path, class: "btn btn-default"%>

<%- end %>

app/views/doctors/show.html.erb
<div>
  <h1 class="page-header">
  	<%= @current_user.name %>
  </h1>

 <table border="2" class="table table-hover table-bordered">
	<thead>
		<tr>
			<th>Email</th>
			<th>Total de Ingresos</th>
		</tr>
	</thead>
	<tbody>
		<td> <%= @current_user.email %> </td>
		<td> <%= @current_user.sum_of_appointments %> </td>
	</tbody>
</table>

<div class="btn-group" role="group" aria-label="Acciones">
<%= link_to "Editar Informacion", edit_profile_path, class: "btn btn-default"  %>
</div>

<%= render partial: "doctor_appointments", locals: {appointments: @doctor.appointments} %>

 </div>

app/views/owners/_form.html.erb
<div class="form-group">
	<%= f.label :name, "Nombre: " %>
	<%= f.text_field :name, class: "form-control"%>
</div>
<div class="form-group">
	<%= f.label :last_name, "Apellido: " %>
	<%= f.text_field :last_name, class: "form-control" %>
</div>
<div class="form-group">
	<%= f.label :address, "Direccion: " %>
	<%= f.text_area :address , class: "form-control"%>
</div>
<div class="form-group">
	<%= f.label :email, "Correo Electronico: " %>
	<%= f.email_field :email , class: "form-control"%>
</div>
<div class="form-group">
	<%= f.label :phone, "Telefono" %>
	<%= f.number_field :phone, class: "form-control" %>
</div>

app/views/owners/_owner.html.erb
<tr>
	<td><%= link_to owner.id, owner %></td>
	<td><%= owner.name %></td>
	<td><%= owner.last_name %></td>
	<td><%= owner.phone %></td>	
<tr>

app/views/owners/edit.html.erb
<h1>Editar Propiestario</h1>

<%= render partial: "shared/errors", locals: { obj: @owner } %>

<%= form_for @owner do |f| %>
	<%= render partial: "form", locals: {f: f} %>
	<div class="btn-group" role="group" aria-label="Acciones">
		<%= button_tag(type: 'submit', class: "btn btn-default") do %>
			<i class="icon-ok icon-white"></i> Actualizar
		<% end %>
		<%= link_to "Cancelar", @owner, class: "btn btn-default"%>
		<%= link_to "Borrar", @owner, method: :delete, data: {confirm: "Estas Seguro?"}, class: "btn btn-default"%>
<%- end %>

app/views/owners/index.html.erb
<%= owner_index_title %>
<%= owner_index_description %>

<hr>

<% if flash[:notice] %>
	<div style="background: yellow">
		<%= flash[:notice] %>
	</div>
<% end %>

<table border="2" class="table table-hover table-bordered">
	<thead>
		<th colspan="3">
			Informacion Personal
		</th>
			<th colspan="1">
			Datos de Contacto
		</th>
		<tr>
			<th>ID</th>
			<th>Nombre</th>
			<th>Apellido</th>
			<th>Telefono</th>
		</tr>
	</thead>
	<tbody>
		<%= render @owners %>
	</tbody>
</table>

<div class="btn-group" role="group" aria-label="Acciones">
	<%= link_to "Agregar Propietario", new_owner_path, class: "btn btn-default"%>
</div>

app/views/owners/new.html.erb
<h1>Crear nuevo Propietario</h1>
<p><em>Ingrese los siguientes datos: </em></p>

<%= render partial: "shared/errors", locals: { obj: @owner } %>

<%= form_for @owner do |f| %>
	<%= render partial: "form", locals: {f: f} %>

<div class="btn-group" role="group" aria-label="Acciones">
	<%= button_tag(type: 'submit', class: "btn btn-default") do %>
			<i class="icon-ok icon-white"></i> Crear Propietario
<% end %>
		<%= link_to "Cancelar", owners_path, class: "btn btn-default"%>

<%- end %>

app/views/owners/owner_pets.html.erb
<h1>Veterinaria Chansey</h1>
<p>Atendido por las mas entrenadas enfermeras Joy</p>

<table border="2" class="table table-hover table-bordered">
	<thead>
			<tr>
				<th>ID</th>
				<th>Nombre</th>
				<th>Animal</th>
				<th>Raza</th>
				<th>Fecha Nacimiento</th>
			</tr>
			</thead>
			<tbody>
			</tbody>
		</table>

</body>

app/views/owners/pets.html.erb
<h1>Veterinaria Chansey</h1>
<p>Atendido por las mas entrenadas enfermeras Joy</p>

<table border="2" class="table table-hover table-bordered">
	<thead>
			<tr>
				<th>ID</th>
				<th>Nombre</th>
				<th>Animal</th>
				<th>Raza</th>
				<th>Fecha Nacimiento</th>
			</tr>
			</thead>
			<tbody>
			<tbody>
				<%= render @pet %>
			</tbody>
			</tbody>
		</table>

</body>

app/views/owners/show.html.erb
<h1><b> <%= @owner.name + " " + @owner.last_name %> </b></h1>

<p> <i> <%= @owner.address %> <i></p>
<hr> </hr>
<ul>
	<li>
		<strong>ID: </strong>
		<%= @owner.id %>
	</li>
	<li>
		<strong>Nombre: </strong>
		<%= @owner.name %>
	</li>
	<li>
		<strong>Apellido: </strong>
		<%= @owner.last_name %>
	</li>
	<li>
		<strong>Email: </strong>
		<%= @owner.email %>
	</li>
	<li>
		<strong>Telefono: </strong>
		<%= @owner.phone %>
	</li>
</ul>

<div class="btn-group" role="group" aria-label="Acciones">
	<%= link_to "Editar Propietario", edit_owner_path, class: "btn btn-default"  %>
	<%= link_to "Eliminar Propietario", @owner, method: :delete, data: {confirm: "Estas Seguro?"}  , class: "btn btn-default"%>
	<%= link_to "Ver Mascotas", pets_owner_path(@owner.id), class: "btn btn-default"  %>

app/views/pets/_form.html.erb
<div class="form-group">
		<%=	f.label :name, "Nombre: " %>
		<%=	f.text_field :name , class: "form-control" %>
	</div>
<div class="form-group">
		<%=	f.label :born_at, "Fecha Nacimiento: " %>
		<%=	f.date_field :born_at, class: "form-control" %>
	</div>
<div class="form-group">
		<%=	f.label :observations, "Observaciones: " %>
		<%=	f.text_area :observations, class: "form-control" %>
	</div>
<div class="form-group">
	<%= f.label :animal_id, "Tipo de Animal" %>
	<%= f.select :animal_id, Animal.pluck(:name, :id), class: "form-control" %>
	</div>
<div class="form-group">
	<%= f.label :breed, "Raza" %>
	<%= f.text_field :breed, class: "form-control" %>
	</div>
<div class="form-group">
	<%= f.label :owner_id, "Propietario" %>
	<%= f.select :owner_id, Owner.pluck(:name, :id), class: "form-control" %>
</div>
<div class="form-group">
		<%=	f.label :pet_url, "Imagen: " %>
		<%=	f.url_field :pet_url, class: "form-control" %>
</div>

app/views/pets/_pet.html.erb
<tr>
	<td><%= link_to pet.id,pet %></td>
	<td><%= pet.name %></td>
	<td><%= pet.animal.name %></td>
	<td><%= pet.breed %></td>
	<td><%= nice_date(pet.born_at)	 %></td>
</tr>

app/views/pets/_pet_appointments.html.erb
<% if appointments.any? %>
	<div>
		<h2>Citas hechas: </h2>
<table border="2" class="table table-hover table-bordered">
			<thead>
				<th>ID</th>
				<th>Fecha</th>
				<th>Doctor</th>
				<th>Monto Pagado</th>
			</thead>
			<tbody>
				<%= render appointments %>
			</tbody>
		</table>
	</div>
<% else %>
	<p><em>No tiene citas registradas aun.</em></p>
<% end %>

app/views/pets/edit.html.erb
<h1>Editar Mascotas</h1>
<p><em>Verificar los siguientes datos: </em></p>

<%= render partial: "shared/errors", locals: { obj: @pet } %>

<%= form_for @pet do |f| %>
	<%= render partial: "form", locals: {f: f} %>


	<div class="btn-group" role="group" aria-label="Acciones">
		<%= button_tag(type: 'submit', class: "btn btn-default") do %>
			<i class="icon-ok icon-white"></i> Actualizar
		<% end %>
		<%= link_to "Cancelar", @pet, class: "btn btn-default" %>

<%- end %>

app/views/pets/index.html.erb
<h1>Veterinaria Chansey</h1>
<p>Atendido por las mas entrenadas enfermeras Joy</p>

	<% if flash[:notice] %>
	<div style="background: yellow">
		<%= flash[:notice] %>
	</div>
<% end %>

<table border="2" class="table table-hover table-bordered">
	<thead>
			<tr>
				<th>ID</th>
				<th>Nombre</th>
				<th>Animal</th>
				<th>Raza</th>
				<th>Fecha Nacimiento</th>
			</tr>
			</thead>
			<tbody>
					<%= render @pets %>
			</tbody>
		</table>

<div class="btn-group" role="group">
	<%= link_to "Nuevo", new_pet_path, class: "btn btn-default" %>
</body>

app/views/pets/new.html.erb
<h1>Crear nueva Mascota</h1>
<p><em>Ingrese los siguientes datos: </em></p>

<%= render partial: "shared/errors", locals: { obj: @pet } %>

<%= form_for @pet do |f| %>
<%= render partial: "form", locals: {f: f} %>
	<p>
<div class="btn-group" role="group" aria-label="Acciones">
		<%= button_tag(type: 'submit', class: "btn btn-default") do %>
			<i class="icon-ok icon-white"></i> Crear Mascota
		<% end %>
		<%= link_to "Cancelar", pets_path, class: "btn btn-default" %>
	</p>
<%- end %>

app/views/pets/show.html.erb
<div class="row"> 
  <div class="col-md-3 col-xs-6"> 
     <a href="#" class="thumbnail"> <img alt="Sin imagen para mostrar" data-src="holder.js/100%x180" style="height: 180px; width: 100%; display: block;" src=<%= @pet.pet_url %> data-holder-rendered="true"> 
     </a> 
  	<div class="caption">
			<h1><b> <%= @pet.name %> </b></h1>
			<p> <i> <%= @pet.observations %> <i></p>
		</div>	
  </div>
</div>

<hr>
<ul>
	<li>
		<strong>ID: </strong>
		<%= @pet.id %>
	</li>
	<li>
		<strong>Animal: </strong>
		<%= @pet.animal.name %>
	</li>
	<li>
		<strong>Raza: </strong>
		<%= @pet.breed %>
	</li>
	<li>
		<strong>Fecha de Nacimiento: </strong>
		<%= nice_date(@pet.born_at) %>
	</li>
	<li>
		<strong>Total en Citas: </strong>
		<%= @pet.sum_of_appointments %>
	</li>
</ul>

<%= render partial: "pet_appointments", locals: {appointments: @pet.appointments} %>

<div class="btn-group" role="group" aria-label="Acciones">
	<%= link_to "Editar Mascota", edit_pet_path, class: "btn btn-default" %>
	<%= link_to "Eliminar Mascota", @pet, method: :delete, data: {confirm: "Estas Seguro?"}, class: "btn btn-default" %>
	<%= link_to "Crear una cita", new_pet_appointment_path(@pet), class: "btn btn-default" %>
</div>